function createDefaultBudget(username) {
    var jsonData = [
        { "category": "shopping", "amount": 500, "month": "January", "type": "budget", "username": username},
        { "category": "housing", "amount": 500, "month": "January", "type": "budget", "username": username},
        { "category": "transportation", "amount": 500, "month": "January", "type": "budget", "username": username},
        { "category": "healthcare", "amount": 500, "month": "January", "type": "budget", "username": username},
        { "category": "other", "amount": 500, "month": "January", "type": "budget", "username": username},
        { "category": "shopping", "amount": 500, "month": "February", "type": "budget", "username": username},
        { "category": "housing", "amount": 500, "month": "February", "type": "budget", "username": username},
        { "category": "transportation", "amount": 500, "month": "February", "type": "budget", "username": username},
        { "category": "healthcare", "amount": 500, "month": "February", "type": "budget", "username": username},
        { "category": "other", "amount": 500, "month": "February", "type": "budget", "username": username},
        { "category": "shopping", "amount": 500, "month": "March", "type": "budget", "username": username},
        { "category": "housing", "amount": 500, "month": "March", "type": "budget", "username": username},
        { "category": "transportation", "amount": 500, "month": "March", "type": "budget", "username": username},
        { "category": "healthcare", "amount": 500, "month": "March", "type": "budget", "username": username},
        { "category": "other", "amount": 500, "month": "March", "type": "budget", "username": username},
        { "category": "shopping", "amount": 500, "month": "April", "type": "budget", "username": username},
        { "category": "housing", "amount": 500, "month": "April", "type": "budget", "username": username},
        { "category": "transportation", "amount": 500, "month": "April", "type": "budget", "username": username},
        { "category": "healthcare", "amount": 500, "month": "April", "type": "budget", "username": username},
        { "category": "other", "amount": 500, "month": "April", "type": "budget", "username": username},
        { "category": "shopping", "amount": 500, "month": "May", "type": "budget", "username": username},
        { "category": "housing", "amount": 500, "month": "May", "type": "budget", "username": username},
        { "category": "transportation", "amount": 500, "month": "May", "type": "budget", "username": username},
        { "category": "healthcare", "amount": 500, "month": "May", "type": "budget", "username": username},
        { "category": "other", "amount": 500, "month": "May", "type": "budget", "username": username},
        { "category": "shopping", "amount": 500, "month": "June", "type": "budget", "username": username},
        { "category": "housing", "amount": 500, "month": "June", "type": "budget", "username": username},
        { "category": "transportation", "amount": 500, "month": "June", "type": "budget", "username": username},
        { "category": "healthcare", "amount": 500, "month": "June", "type": "budget", "username": username},
        { "category": "other", "amount": 500, "month": "June", "type": "budget", "username": username},
        { "category": "shopping", "amount": 500, "month": "July", "type": "budget", "username": username},
        { "category": "housing", "amount": 500, "month": "July", "type": "budget", "username": username},
        { "category": "transportation", "amount": 500, "month": "July", "type": "budget", "username": username},
        { "category": "healthcare", "amount": 500, "month": "July", "type": "budget", "username": username},
        { "category": "other", "amount": 500, "month": "July", "type": "budget", "username": username},
        { "category": "shopping", "amount": 500, "month": "August", "type": "budget", "username": username},
        { "category": "housing", "amount": 500, "month": "August", "type": "budget", "username": username},
        { "category": "transportation", "amount": 500, "month": "August", "type": "budget", "username": username},
        { "category": "healthcare", "amount": 500, "month": "August", "type": "budget", "username": username},
        { "category": "other", "amount": 500, "month": "August", "type": "budget", "username": username},
        { "category": "shopping", "amount": 500, "month": "September", "type": "budget", "username": username},
        { "category": "housing", "amount": 500, "month": "September", "type": "budget", "username": username},
        { "category": "transportation", "amount": 500, "month": "September", "type": "budget", "username": username},
        { "category": "healthcare", "amount": 500, "month": "September", "type": "budget", "username": username},
        { "category": "other", "amount": 500, "month": "September", "type": "budget", "username": username},
        { "category": "shopping", "amount": 500, "month": "October", "type": "budget", "username": username},
        { "category": "housing", "amount": 500, "month": "October", "type": "budget", "username": username},
        { "category": "transportation", "amount": 500, "month": "October", "type": "budget", "username": username},
        { "category": "healthcare", "amount": 500, "month": "October", "type": "budget", "username": username},
        { "category": "other", "amount": 500, "month": "October", "type": "budget", "username": username},
        { "category": "shopping", "amount": 500, "month": "November", "type": "budget", "username": username},
        { "category": "housing", "amount": 500, "month": "November", "type": "budget", "username": username},
        { "category": "transportation", "amount": 500, "month": "November", "type": "budget", "username": username},
        { "category": "healthcare", "amount": 500, "month": "November", "type": "budget", "username": username},
        { "category": "other", "amount": 500, "month": "November", "type": "budget", "username": username},
        { "category": "shopping", "amount": 500, "month": "December", "type": "budget", "username": username},
        { "category": "housing", "amount": 500, "month": "December", "type": "budget", "username": username},
        { "category": "transportation", "amount": 500, "month": "December", "type": "budget", "username": username},
        { "category": "healthcare", "amount": 500, "month": "December", "type": "budget", "username": username},
        { "category": "other", "amount": 500, "month": "December", "type": "budget", "username": username}
    ];
    return jsonData;
}

module.exports = {createDefaultBudget};
